---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# baizer

<!-- badges: start -->
<!-- badges: end -->

The goal of `baizer` is to ...

## installation

You can install the development version of `baizer` like so:

``` r
devtools::install_github("william-swl/baizer")
```

## basic utils
```{r basic-utils}
library(baizer)

# use %nin% to get 'not in' logical value

1 %nin% c(1,2,3)

1 %nin% c(2,3)


# use %!=na% to get NA supported 'not equal' logical value

NA != 0

NA != NA

NA %!=na% 0

NA %!=na% NA


# dump a vector into string

vector_dump(c('A'=2, 'B'=3, 'C'=4), former_name = TRUE,  collapse=';')

vector_dump(c('A'=2, 'B'=3, 'C'=4), former_name = FALSE,  collapse=',')


# return the index of nth different character, return all the indices by default

diff_index('ATTG', 'ATAC')

diff_index('ATTG', 'ATAC', nth=1)

diff_index('ATTG', 'ATAC', nth=2)

```


## numbers
```{r numbers}
# better round string

round(2.1951, 2)

round_string(2.1951, 2)

# better signif string

signif(2.1951, 3)

signif_string(2.1951, 3)

# signif or round string depend on the character length

signif_round_string(20.526, 2, 'short')
signif_round_string(20.526, 2, 'long')

# but will keep the raw value if necessary

signif_round_string(0.000002, 3)

# whether the number string only have zero

is.all_zero('0.000')

is.all_zero('0.0001')

# float number to percent

float_to_percent(0.123, digits=1)

# percent number to float

percent_to_float('123%', digits=3)

```

## dataframe
```{r dataframe}
# dataset

head(mini_diamond)

# shortcut of dplyr::column_to_rownames

head(mini_diamond) %>% c2r('id')

# shortcut of dplyr::rownames_to_column

head(mini_diamond) %>% c2r('id') %>% r2c('id')

# better count to show a main column and a fine column

fancy_count(mini_diamond, 'cut', 'clarity')

fancy_count(mini_diamond, 'cut', 'clarity', sort=TRUE)

fancy_count(mini_diamond, 'cut', 'clarity', fine_fmt='ratio')

fancy_count(mini_diamond, 'cut', 'clarity', fine_fmt='clean')

```
